/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c SessionDbusAdaptor -a SessionDbusAdaptor_p.h:SessionDbusAdaptor.cpp com.control.center.qt.sessiondbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "SessionDbusAdaptor_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SessionDbusAdaptor
 */

SessionDbusAdaptor::SessionDbusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SessionDbusAdaptor::~SessionDbusAdaptor()
{
    // destructor
}

void SessionDbusAdaptor::getModuleHideStatus()
{
    // handle method call com.control.center.qt.sessiondbus.getModuleHideStatus
    QMetaObject::invokeMethod(parent(), "getModuleHideStatus");
}

