/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c SessionDbusAdaptor -a SessionDbusAdaptor_p.h:SessionDbusAdaptor.cpp com.control.center.qt.sessiondbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SESSIONDBUSADAPTOR_P_H
#define SESSIONDBUSADAPTOR_P_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.control.center.qt.sessiondbus
 */
class SessionDbusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.control.center.qt.sessiondbus")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.control.center.qt.sessiondbus\">\n"
"    <method name=\"getModuleHideStatus\"/>\n"
"  </interface>\n"
        "")
public:
    SessionDbusAdaptor(QObject *parent);
    virtual ~SessionDbusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void getModuleHideStatus();
Q_SIGNALS: // SIGNALS
};

#endif
