name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout ukui-control-center source
      uses: actions/checkout@v2

    - name: Update apt repository
      run: sudo apt-get update -y

    - name: Install latest Qt5
      run: sudo apt-get -y install build-essential qt5-default qttools5-dev-tools

    - name: Instal dependcies
      run: sudo apt-get install pkg-kde-tools pkg-config libkf5widgetsaddons-dev libkf5config-dev libkf5configwidgets-dev libkf5screen-dev debhelper-compat libqt5svg5-dev libgsettings-qt-dev libglib2.0-dev libmatekbd-dev libqt5x11extras5-dev libxklavier-dev qtdeclarative5-dev libdconf-dev libmatemixer-dev libqt5xdg-dev qtmultimedia5-dev libxml2-dev libcanberra-dev

    - name: QMake configure & Make
      run: mkdir build && cd build && qmake .. && make -j$(nproc)
